# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
                
target 'mapTrackerApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic   frameworks
  # use_frameworks!
                
  # Pods for mapTrackerApp
  target 'mapTrackerApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
                
 
                
  react_native_path = "../node_modules/react-native"
  pod "yoga", :path => "#{react_native_path}/ReactCommon/yoga"
  pod "React", :path => react_native_path
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'lottie-ios', :path => '../node_modules/lottie-ios'
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  
 

end
